CREATE DATABASE GERENCIADOR_TAREFAS;
USE GERENCIADOR_TAREFAS;

CREATE TABLE TREFA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDNETE',
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);